[package]
name = "firemage-webui-page-vms"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
dioxus = { workspace = true }
serde_json = { workspace = true }
firemage-webui-provider-api = { path = "../provider-api" }
firemage-webui-provider-auth = { path = "../provider-auth" }
firemage-webui-component-controls = { path = "../component-controls" }
firemage-webui-view-vm-detail = { path = "../view-vm-detail" }
firemage-webui-view-vm-editor = { path = "../view-vm-editor" }
gloo-timers = { version = "0.3", features = ["futures"] }
