[package]
name = "firemage-webui-view-vm-editor"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
dioxus = { workspace = true }
serde_json = { workspace = true }
firemage-webui-provider-api = { path = "../provider-api" }
firemage-webui-provider-auth = { path = "../provider-auth" }
firemage-webui-component-controls = { path = "../component-controls" }
toml = { workspace = true }
firemage-wire = { path = "../../crates/wire" }
firemage-webui-view-security = { path = "../view-security" }
firemage-webui-view-asset-attachments = { path = "../view-asset-attachments" }
firemage-webui-view-egress = { path = "../view-egress" }
firemage-webui-view-environment = { path = "../view-environment" }
firemage-webui-view-boot = { path = "../view-boot" }
web-sys = { workspace = true, features = ["Window", "Document", "Element"] }

firemage-webui-view-web-shell = { path = "../view-web-shell" }
