[package]
name = "firemage-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
firemage-guest-bundle = { path = "../guest-bundle" }
firemage-guest-protocol = { path = "../guest-protocol" }
base64 = "0.22"
hex.workspace = true
firemage-catalog-files = { path = "../catalog-files" }
firemage-snapshots = { path = "../snapshots" }
firemage-kernels = { path = "../kernels" }
anyhow.workspace = true
tokio.workspace = true
serde_json.workspace = true
toml.workspace = true
sha2.workspace = true
uuid.workspace = true
firemage-wire = { path = "../wire" }
firemage-queries = { path = "../queries" }
firemage-orm = { path = "../orm" }
firemage-firecracker = { path = "../firecracker" }
firemage-assets = { path = "../assets" }
firemage-network = { path = "../network" }
firemage-config = { path = "../config" }
libc = "0.2"

firemage-egress-proxy = { path = "../egress-proxy" }
firemage-secrets = { path = "../secrets" }

tempfile.workspace = true

[dev-dependencies]
axum.workspace = true
