[package]
name = "firemage-kernels"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
firemage-catalog-files = { path = "../catalog-files" }
anyhow.workspace = true
firemage-wire = { path = "../wire" }
tempfile.workspace = true

[dev-dependencies]
tokio.workspace = true
