[package]
name = "firemage-secrets"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
firemage-queries = { path = "../queries" }
firemage-request-signing = { path = "../request-signing" }
firemage-wire = { path = "../wire" }
chacha20poly1305 = "0.10"
rand.workspace = true
hex.workspace = true
libc = "0.2"
zeroize = "1"
async-trait = "0.1"
tempfile.workspace = true

[dev-dependencies]
tokio.workspace = true
